
clear
close all

% set constants
altitude=1; % Mean Earth radius multiple
cgrid=true; % plot c-grid coastline

% define contours
ref=0;

gridloc1='/Users/afroberts/SIhMSatArray/E3SM/Greenland/grid';
gridfile1='initial_state.nc';
titlename1='JIGSAW Greenland';

gridloc2='/Users/afroberts/SIhMSatArray/E3SM/Greenland/grid';
gridfile2='greenland_grid.nc';
titlename2='MPAS Greenland';

% plot location
centlat=30;
centlon=40;
horizon=20;

% obtain grid information
cd(gridloc1)
ncvert=ridgepack_clone(gridfile1,{'latVertex','lonVertex',...
                                  'dcEdge',...
                                  'verticesOnCell',...
                                  'indexToCellID',...
                                  'nEdgesOnCell',...
                                  'edgesOnCell',...
                                  'cellsOnEdge',...
                                  'areaCell',...
                                  'weightsOnEdge'});

nccell=ridgepack_clone(gridfile1,{'latCell',...
                                  'lonCell',...
                                  'areaCell'});


ridgepack_multiplot(1,2,1,1,'a')
ridgepack_satview(centlat,centlon,horizon,1,0);
ridgepack_psatmeshe3sm(nccell,'areaCell',ncvert,...
                       centlat,centlon,horizon,altitude);
ridgepack_psatcoaste3sm(ncvert,cgrid,'JIGSAW_Greenland',...
                        centlat,centlon,horizon);
title([titlename1,...
      ' (',num2str(length(nccell.latitude.data)),...
      ' total cells)'],'FontSize',10) 

cd(gridloc2)
ncvert=ridgepack_clone(gridfile2,{'latVertex','lonVertex',...
                                  'dcEdge',...
                                  'verticesOnCell',...
                                  'indexToCellID',...
                                  'nEdgesOnCell',...
                                  'edgesOnCell',...
                                  'cellsOnEdge',...
                                  'areaCell',...
                                  'weightsOnEdge'});

nccell=ridgepack_clone(gridfile2,{'latCell',...
                                  'lonCell',...
                                  'areaCell'});


ridgepack_multiplot(1,2,1,2,'b')
ridgepack_satview(centlat,centlon,horizon,1,0);
ridgepack_psatmeshe3sm(nccell,'areaCell',ncvert,...
                       centlat,centlon,horizon,altitude);
ridgepack_psatcoaste3sm(ncvert,cgrid,'MPAS_Greenland',...
                        centlat,centlon,horizon);
title([titlename2,...
      ' (',num2str(length(nccell.latitude.data)),...
      ' total cells)'],'FontSize',10) 

ridgepack_multialign(gcf)

cd('/users/afroberts/work')

ridgepack_fprint('png','JIGSAW_MPAS_Comparison',1,2)


